spring:
  datasource:
    # 数据源基本配置
    username: se
    password: sepwd123
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://193.112.33.53/whufleamarket
    type: com.alibaba.druid.pool.DruidDataSource
    schema:
      - classpath:schemas/ProductCategory.sql
      - classpath:schemas/PersonInfo.sql
      - classpath:schemas/Product.sql
      - classpath:schemas/ProductImg.sql
    initialization-mode: always
# SpringMVC 配置
server:
  servlet:
    # 统一在 url 加上 /whufleamarket 前缀
    context-path: /whufleamarket
